import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` w-screen flex h-screen ${inter.className}`}>
        <div className="max-w-[272px]">
          <Navbar />
        </div>
        <div className="w-full">
          {children}
        </div>
      </body>
    </html>
  );
}
